# Generated by Django 3.1.14 on 2023-04-28 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_house'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='house',
            table='houses',
        ),
    ]
