# Generated by Django 3.1.14 on 2023-04-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20230428_1542'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='house',
            table=None,
        ),
    ]
