# Generated by Django 3.1.14 on 2023-04-28 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20230428_1551'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='house',
            table='house',
        ),
    ]
